### ISSUE TITLE
translation problems

### ISSUE THREAD

**Issue by sx-y** [Kerilk/bayonetta_tools#4]
Your tools are very useful and I've managed to extract many files. Sadly I did't find files like text. I think their name should inclued _us _fr etc. May I ask for some help find the text files?

**Comment by Kerilk** [comment]
Is it for Bayo 2 or Bayo 1?

**Comment by sx-y** [comment]
Thanks for reply! It's for Bayo 2.

**Comment by sx-y** [comment]
> Is it for Bayo 2 or Bayo 1?

Thanks for reply! It's for Bayo 2.

**Comment by Kerilk** [comment]
Then you are in luck, I reversed engineered the format last month. You can view the subtitles track using the
[Bayonetta 2 Switch mcd.bt](https://github.com/Kerilk/bayonetta_tools/blob/master/binary_templates/Bayonetta%202%20Switch%20mcd.bt) or [Bayonetta 2 mcd.bt](https://github.com/Kerilk/bayonetta_tools/blob/master/binary_templates/Bayonetta%202%20mcd.bt) binary templates depending if you are working on the Switch or WiiU version.
You need to use [010Editor](https://www.sweetscape.com/010editor/) to use the templates.

Those files are in the data003.cpk file in the Evm directory. You have one file per event and language.
Each file will contain an msq file, an mcd file and a texture (contained in the wta/wtp). The subtitles are based on bitmap font.
 - the texture is a bitmap font restricted to the characters used int the event messages
 - the msq is list of time point during the event, a subtitle can appear at the different time points (note that the only complete msq file is the japanese one, the localized one only reference the time points they use)
 - the mcd file contains the messages, but also the position of the different code points in the bitmap.

The first event Japanese bitmap font image is this one (without the alpha channel):

![event_0000_000 - Copy](https://user-images.githubusercontent.com/1815142/57868817-fb6d7380-7803-11e9-96e6-7cc0aae416cb.png)

And the mcd file for the first event, where you can find the list of characters used:
![characters](https://user-images.githubusercontent.com/1815142/57867839-23f46e00-7802-11e9-916d-dfe48a60152e.png)
And the messages (here French and Japanese introduction):
![translation](https://user-images.githubusercontent.com/1815142/57869097-91a19980-7804-11e9-80c3-26ab3b454c72.png)
And the code point coordinates in the image:
![coordinates](https://user-images.githubusercontent.com/1815142/57869208-d4fc0800-7804-11e9-92f7-91f8a6b5fed6.png)

**Comment by sx-y** [comment]
> Then you are in luck, I reversed engineered the format last month. You can view the subtitles track using the
> [Bayonetta 2 Switch mcd.bt](https://github.com/Kerilk/bayonetta_tools/blob/master/binary_templates/Bayonetta%202%20Switch%20mcd.bt) or [Bayonetta 2 mcd.bt](https://github.com/Kerilk/bayonetta_tools/blob/master/binary_templates/Bayonetta%202%20mcd.bt) binary templates depending if you are working on the Switch or WiiU version.
> You need to use [010Editor](https://www.sweetscape.com/010editor/) to use the templates.
> 
> Those files are in the data003.cpk file in the Evm directory. You have one file per event and language.
> Each file will contain an msq file, an mcd file and a texture (contained in the wta/wtp). The subtitles are based on bitmap font.
> 
> * the texture is a bitmap font restricted to the characters used int the event messages
> * the msq is list of time point during the event, a subtitle can appear at the different time points (note that the only complete msq file is the japanese one, the localized one only reference the time points they use)
> * the mcd file contains the messages, but also the position of the different code points in the bitmap.
> 
> The first event Japanese bitmap font image is this one (without the alpha channel):
> 
> ![event_0000_000 - Copy](https://user-images.githubusercontent.com/1815142/57868817-fb6d7380-7803-11e9-96e6-7cc0aae416cb.png)
> 
> And the mcd file for the first event, where you can find the list of characters used:
> ![characters](https://user-images.githubusercontent.com/1815142/57867839-23f46e00-7802-11e9-916d-dfe48a60152e.png)
> And the messages (here French and Japanese introduction):
> ![translation](https://user-images.githubusercontent.com/1815142/57869097-91a19980-7804-11e9-80c3-26ab3b454c72.png)
> And the code point coordinates in the image:
> ![coordinates](https://user-images.githubusercontent.com/1815142/57869208-d4fc0800-7804-11e9-92f7-91f8a6b5fed6.png)

Thank you for your hlep! I've extrated all the subtitle today! There are still some problems: When I tried to extrac the illustration of costumes, the text seems wrong. Could you please help me with that?
![image](https://user-images.githubusercontent.com/50708946/57917926-56689e80-78c8-11e9-865d-fa3bd82efac9.png)

**Comment by Kerilk** [comment]
What file are you trying to read?

**Comment by sx-y** [comment]
> What file are you trying to read?
mmCHA001.mcd  I put a copy in google drive.
https://drive.google.com/file/d/1FwSTXfwYVbERCFuG9toULHFjerGx-P1s/view?usp=sharing

**Comment by Kerilk** [comment]
Okay, I pushed a fix for this file. The problem comes from special characters in the text. Here, it was a left stick icon. I replaced it with the <LeftStick> token.
There must be one for each button of the switch controller. Please report any other file that fail so that I can add the correct tokens for the missing buttons.

**Comment by sx-y** [comment]
Thank you, The new templates works well. May I ask another stupid question about the .mcd? The mcd files contain the charactor that it used. I extracted a WiiU version of translation, but I still can't figure it out what these means.
![image](https://user-images.githubusercontent.com/50708946/57964506-08f03e00-7969-11e9-8349-f44d6f18cca4.png)
![image](https://user-images.githubusercontent.com/50708946/57964514-173e5a00-7969-11e9-86fe-d94011170332.png)
Thanks again for your patience and marvelous work.

**Comment by Kerilk** [comment]
I added more comments and renamed what I understood/guessed. Can you update the templates and then ask me questions about which specific fields you don't understand?

**Comment by sx-y** [comment]
I'm sorry I didn't get things clearly before asking questions. I realized my questions are not about the tools themselves, it's irresponsible to ask them to the owner.
What I want to say is another bug, I'm sure I used the updated templete, but there are still bugs. 
![image](https://user-images.githubusercontent.com/50708946/57971971-92cef400-79c7-11e9-902c-8ad75b116047.png)
I put a copy in google drive: 
https://drive.google.com/file/d/1ekcQyF9G2X4U3I7VxtTbiylWBZG0E2Sc/view?usp=sharing
Thanks again.

**Comment by Kerilk** [comment]
I updated the templates again. The button recognition should be better. If you manage to identify unidentified buttons or mislabeled ones please report them.

As far as questions are concerned it was just that your question was too vague for me to answer it. I don't know what you understood of the format or not so I can't adjust my answers.

**Comment by sx-y** [comment]
I've tried the updated templates, it seems all the buttons are correctly recognized. 
Thanks to your work and patience.
